# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"

  # This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository
      - uses: actions/checkout@v3
      # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: sandipshrest
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Shows the status of the build
      - run: git status

      # Push the changes to the main branch
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}
          branch: main
          force: true

      # Deploys the snake gif and svg to GitHub Pages (on the "output" branch)
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}


